<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PlcPack" Id="{8facb200-c082-02e8-236e-e0e530d5058a}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK PlcPack IMPLEMENTS I_GraphPack
VAR
	plcDatatypePack : PlcDatatypePack;
	plcNodePack : PlcNodePack;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Register" Id="{849d8d36-3b49-0956-0a19-56aa05b3bf95}">
      <Declaration><![CDATA[METHOD Register
VAR_INPUT
	Datatypes : I_Datatypes;
	NodeFactory : I_NodeFactory;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[plcDatatypePack.RegisterWithDatatypes(Datatypes);
plcNodePack.RegisterWithNodeFactory(NodeFactory);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>