<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="HardwareNode" Id="{8a18619e-3bff-0ee0-18d6-780ce4fc0c54}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT HardwareNode EXTENDS Node

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Clone" Id="{cec82d75-f155-4784-a43d-387f9ee1bdac}">
      <Declaration><![CDATA[METHOD PUBLIC Clone : I_Node
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Clone := THIS^;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Dispose" Id="{7708a250-3ac6-4df8-aaf2-fad4b0369d75}">
      <Declaration><![CDATA[METHOD Dispose
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>